### ISSUE TITLE
Improvement (draft)

### ISSUE THREAD

**Issue by sabrinatkk** [UBC-MDS/DSCI_532_Mental-health-survey-Tech#17]
Improvement completed:

- "all" button is added to Country and Gender filters.
- Font size on labels on axes.
- Added Dropdown menu for Attitude. This contains all the questions we included in the presentation.

**Comment by panntingg** [comment]
From TA's feedback of Millstone 2:
- [ ] Include a code of conduct.

- [ ] The app has too many plots, you can probably use facet wrap to display them in a 2x2 instead of scrolling so much. You might want to consider a selection of variables to limit the number of plots displayed at once.

- [ ] Increase the size of the axis and label x axis.

- [ ] I recommend including a dropdown menu for country selection or a text widget to select multiple countries at once instead of the radio buttons.

- [ ] Maybe change the gender selection to checkboxes to allow seeing trends for all genders.

- [ ] Your code has minimal comments, try to add some more.

- [ ] The new lines between code lines are unnecessary and makes the code really hard to read.

**Comment by sabrinatkk** [comment]
Thank you @panntingg !

**Comment by sabrinatkk** [comment]
Please review our [milestone 3 writeup](https://github.com/UBC-MDS/DSCI_532_Mental-health-survey-Tech/blob/master/doc/Milestone_3.md) and [app](https://panntingg.shinyapps.io/mental_health_app_3_0/) that has reflected on your suggestion.
